server:
  port: 8080

api:
  weather:
    url: https://api.openweathermap.org/data/2.5/weather
    key: dd1bcbedfd4e5f6b3d787437a740b2ca

scheduler:
  refresh:
    interval: 3600000 # Executes every hour (in milliseconds)

  datasource:
    url: jdbc:h2:mem:weatherdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update